version: '3'
services:
  scraper:
    build: .
    environment:
      - URL_BASE=https://www.farmatodo.com.co/categorias/salud-y-medicamentos
    volumes:
      - ./data:/app/data
      - ./data/db:/var/opt/mssql/data
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - ./data/db:/var/opt/mssql/data