version: '3'
services:
  scraper:
    build: .
    ports:
      - "5000:5000"
    environment:
      - URL_BASE=https://www.farmatodo.com.co/categorias/salud-y-medicamentos
    volumes:
      - .:/app