version: '3'
services:
  scraper:
    build: .
    environment:
      - URL_BASE=https://www.farmatodo.com.co/categorias/salud-y-medicamentos
    volumes:
      - ./data:/app/data
    command: ["python", "app/app.py"]